### ISSUE TITLE
Requirement no.16 

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/andi#10]
@Nanouk123 This requirement could be again coupled to the "," for csv or ";" for dutch. At present the default date format is ""YYYY-MM-DD" however the presentation(looks) is "MM-DD-YYYY". Based on the selection by user ","  or ";" we can change the looks of date filed in ?

**Comment by Nanouk123** [comment]
Dutch system is dd/mm/yyyy.

**Comment by anandgavai** [comment]
so you mean we keep it same for both  "dd/mm/yyyy" ?

**Comment by Nanouk123** [comment]
I think so, my excel autocorrects to this format so its even a bit difficult to type in another format.  We could always explicitly ask the clinician how they formatted the date.

**Comment by anandgavai** [comment]
OK !
