### ISSUE TITLE
Requirement no.7

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/andi#7]
@Nanouk123  This feature sill require more development as there are more complexities involved with regard to user management at this moment we are not certain if we should do it !

**Comment by Nanouk123** [comment]
At this point you dont need to log in. But we doo need this function at some point (else anyone could use andi which we don't want). After logging in you could keep some list of preferred tests. This will increase user friendliness since we will add many more tests.

**Comment by anandgavai** [comment]
@Nanouk123 I cannot comment on this right now I will have to check out our options !

**Comment by Nanouk123** [comment]
You don't have to comment on this right now. I just replied to give you more information/context

**Comment by mkuzak** [comment]
this might be possible without user management, if we use local browser storage, the page will 'remember' last used tests on this browser and this computer
